### ISSUE TITLE
Confusion on Chapter 03 (Godot 3.2.2 stable)

### ISSUE THREAD

**Issue by DePingus** [Bozar/GodotRoguelikeTutorial#4]
`There are two more post-processing steps. Change PC's color to ABB2BF. Save the node as a scene (PC.tscn) in sprite folder. Repeat these steps until your demo looks like the image below. Note that Floor sprite has a greyish color: 495162.`

Forgive me if these are basic Godot questions (the rest of the tutorial seems to break things down for beginners):

* Where do I do these "post-processing steps"? Specifically...
* Where do I change PC node's color to ABB2BF?
* How do I save the PC Sprite node as a scene?

**Comment by Bozar** [comment]
> Where do I do these "post-processing steps"? Specifically...

You need to save the PC sprite as a scene in Godot engine. But you can change node color either inside game engine or through scripts.

> How do I save the PC Sprite node as a scene?

Right click the PC sprite in Godot engine. In the drop down menu, select Save Branch as Scene.

> Where do I change PC node's color to ABB2BF?

Solution 1. In Godot engine, select PC node. In the `Inspector` panel, set `Modulate` to a given color. You can find this property directly or use the filter textbox. Note that `Modulate` is different from `Self Modulate`. The second property does not affect PC's child node.

Solution 2. Here is a sample script to change color. It is not mentioned in the tutorial.

    var my_sprite: Sprite = get_sprite_from_somewhere_else()
    my_sprite.modulate = "ABB2BF"

**Comment by Bozar** [comment]
I have updated the tutorial. Feel free to check it for a slightly more detailed explanation.

**Comment by DePingus** [comment]
Yes! Thank you. This is perfect!
